# Generated by Django 2.0.2 on 2018-02-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguist', '0002_auto_20180213_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalword',
            name='pronunciation',
            field=models.CharField(default='No pronunciation', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(default='No pronunciation', max_length=100),
        ),
    ]
