# Generated by Django 2.0.2 on 2018-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.IntegerField(default=0),
        ),
    ]
