# Generated by Django 2.0.7 on 2018-08-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='terms_check',
            field=models.BooleanField(default=True),
        ),
    ]
