sudo: false

language: python

python:
  - "3.7"

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd frontend
  - nvm install 14
  - npm install

script:
  - cd -
  - python manage.py test
  - cd frontend
  - npm run test