version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - "./backend:/usr/src/app"
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:3000"
    volumes:
      - "./frontend/:/usr/src/app"
    depends_on:
      backend:
        condition: service_started



volumes:
  db-data: {}