"""
File with list of words for GlobalWord model.
Dictionary format: {'name': '','translation': '','pronunciation': '','language': '','category': '',}
"""
ja_words = [
    {'name': 'あいさつ','translation': 'Greetings','pronunciation': 'Aisatsu','language': 'ja','category': 'Greetings'},
    {'name': 'おはよう','translation': 'good morning','pronunciation': 'Ohayō','language': 'ja','category': 'Greetings'},
    {'name': 'おはよう　ございます','translation': 'good morning polite','pronunciation': 'Ohayōgozaimasu','language': 'ja','category': 'Greetings'},
    {'name': 'こんにちは', 'translation': 'good afternoon', 'pronunciation': 'Konnichiwa', 'language': 'ja','category': 'Greetings'},
    {'name': 'こんばんは', 'translation': 'good evening', 'pronunciation': 'Konbanwa', 'language': 'ja','category': 'Greetings'},
    {'name': 'さようなら', 'translation': 'goodbye', 'pronunciation': 'Sayōnara', 'language': 'ja','category': 'Greetings'},
    {'name': 'おやすみなさい', 'translation': 'good night', 'pronunciation': 'Oyasuminasai', 'language': 'ja','category': 'Greetings'},
    {'name': 'ありがとう', 'translation': 'Thank you', 'pronunciation': 'Arigatō', 'language': 'ja','category': 'Greetings'},
    {'name': 'ありがとう ございます', 'translation': 'Thank you polite', 'pronunciation': 'Arigatōgozaimasu', 'language': 'ja','category': 'Greetings'},
    {'name': 'すみません', 'translation': 'Excuse me', 'pronunciation': 'Sumimasen', 'language': 'ja','category': 'Greetings'},
    {'name': 'いいえ', 'translation': 'No, not at all', 'pronunciation': 'Īe', 'language': 'ja','category': 'Greetings'},
    {'name': 'いってきます', 'translation': 'See you', 'pronunciation': 'Itte kimasu', 'language': 'ja','category': 'Greetings'},
    {'name': 'いってらっしゃい', 'translation': 'Take care', 'pronunciation': 'Itte rasshai', 'language': 'ja', 'category': 'Greetings'},
    {'name': 'ただいま', 'translation': 'I\'m home', 'pronunciation': 'Tadaima', 'language': 'ja', 'category': 'Greetings'},
    {'name': 'おかえりなさい', 'translation': 'Welcome home', 'pronunciation': 'Okaerinasai', 'language': 'ja', 'category': 'Greetings'},
    {'name': 'いただきます', 'translation': 'Thank you for the meal(before)', 'pronunciation': 'Itadakimasu', 'language': 'ja', 'category': 'Greetings'},
    {'name': 'ごちそうさまでした', 'translation': 'Thank you for the meal (after)', 'pronunciation': 'Gochisōsamadeshita', 'language': 'ja', 'category': 'Greetings'},
    {'name': 'はじめまして', 'translation': 'Nice to meet you', 'pronunciation': 'Hajimemashite', 'language': 'ja', 'category': 'Greetings'},
    {'name': 'あたらしいともだち', 'translation': 'New Friends', 'pronunciation': 'Atarashī tomodachi', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'あの', 'translation': 'um', 'pronunciation': 'Ano', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'いま', 'translation': 'now', 'pronunciation': 'Ima', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'えいご', 'translation': 'English', 'pronunciation': 'Ei go', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'ええ', 'translation': 'yes', 'pronunciation': 'E e', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'がくせい', 'translation': 'student', 'pronunciation': 'Gaku see', 'language': 'ja', 'category': 'New Friends'},
    {'name': '〜ご', 'translation': '...language', 'pronunciation': '〜 Go', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'こうこう', 'translation': 'high school', 'pronunciation': 'Kō kō', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'ごご', 'translation': 'p.m.', 'pronunciation': 'Go go', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'ごぜん', 'translation': 'a.m.', 'pronunciation': 'Go zen', 'language': 'ja', 'category': 'New Friends'},
    {'name': '〜さい', 'translation': '...years old', 'pronunciation': '〜 Sai', 'language': 'ja', 'category': 'New Friends'},
    {'name': '〜さん', 'translation': '...Mr.|Ms.', 'pronunciation': '〜-San', 'language': 'ja', 'category': 'New Friends'},
    {'name': '〜じ', 'translation': 'o\'clock', 'pronunciation': '〜Ji', 'language': 'ja', 'category': 'New Friends'},
    {'name': '〜じん', 'translation': '..people', 'pronunciation': '〜 Jin', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'せんこう', 'translation': 'major', 'pronunciation': 'Senkō', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'せんせい', 'translation': 'teacher', 'pronunciation': 'Sensei', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'そうです', 'translation': 'that\'s right', 'pronunciation': 'Sōdesu', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'そうですか', 'translation': 'Is that so?', 'pronunciation': 'Sōdesu ka', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'だいがく', 'translation': 'university', 'pronunciation': 'Dai gaku', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'でんわ', 'translation': 'telephone', 'pronunciation': 'Denwa', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'ともだち', 'translation': 'friend', 'pronunciation': 'Tomodachi', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'なまえ', 'translation': 'name', 'pronunciation': 'Na ma e', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'なん', 'translation': 'what', 'pronunciation': 'Nan', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'なに', 'translation': 'what', 'pronunciation': 'nani', 'language': 'ja', 'category': 'New Friends'},
    {'name': '〜ねんせい', 'translation': 'year student', 'pronunciation': '〜 Nen sei', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'はい', 'translation': 'yes', 'pronunciation': 'Hai', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'はん', 'translation': 'half', 'pronunciation': 'Han', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'ばんごう', 'translation': 'number', 'pronunciation': 'Ban gou', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'りゅうがくせい', 'translation': 'international student', 'pronunciation': 'Ryuugakusei', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'わたし', 'translation': 'I', 'pronunciation': 'Watashi', 'language': 'ja', 'category': 'New Friends'},
    {'name': 'アメリカ', 'translation': 'U.S.A.', 'pronunciation': 'Amerika', 'language': 'ja', 'category': 'Countries'},
    {'name': 'イギリス', 'translation': 'Britian', 'pronunciation': 'Igirisu', 'language': 'ja', 'category': 'Countries'},
    {'name': 'オーストラリア', 'translation': 'Australia', 'pronunciation': 'Ōsutoraria', 'language': 'ja', 'category': 'Countries'},
    {'name': 'かんこく', 'translation': 'Korea', 'pronunciation': 'Kan koku', 'language': 'ja', 'category': 'Countries'},
    {'name': 'スウェーデン', 'translation': 'Sweden', 'pronunciation': 'Suu~ēden', 'language': 'ja', 'category': 'Countries'},
    {'name': 'ちゅうごく', 'translation': 'China', 'pronunciation': 'Chyuugoku', 'language': 'ja', 'category': 'Countries'},
    {'name': 'にほん', 'translation': 'Japan', 'pronunciation': 'Ni hon', 'language': 'ja', 'category': 'Countries'},
    {'name': 'かがく', 'translation': 'science', 'pronunciation': 'Ka gaku', 'language': 'ja', 'category': 'Majors'},
    {'name': 'アジアけんきゅう', 'translation': 'asian studies', 'pronunciation': 'Ajia kenkyū', 'language': 'ja', 'category': 'Majors'},
    {'name': 'けいざい', 'translation': 'economics', 'pronunciation': 'Keizai', 'language': 'ja', 'category': 'Majors'},
    {'name': 'こくさいかんけい', 'translation': 'international relations', 'pronunciation': 'Ko kusai kan kei', 'language': 'ja', 'category': 'Majors'},
    {'name': 'コンピューター', 'translation': 'computer', 'pronunciation': 'Konpyūtā', 'language': 'ja', 'category': 'Majors'},
    {'name': 'じんるいがく', 'translation': 'anthropology', 'pronunciation': 'Jin rui gaku', 'language': 'ja', 'category': 'Majors'},
    {'name': 'せいじ', 'translation': 'politics', 'pronunciation': 'Seiji', 'language': 'ja', 'category': 'Majors'},
    {'name': 'ビジネス', 'translation': 'business', 'pronunciation': 'Bijinesu', 'language': 'ja', 'category': 'Majors'},
    {'name': 'ぶんがく', 'translation': 'literature', 'pronunciation': 'Bun gaku', 'language': 'ja', 'category': 'Majors'},
    {'name': 'れきし', 'translation': 'history', 'pronunciation': 'Rekishi', 'language': 'ja', 'category': 'Majors'},
    {'name': 'しごと', 'translation': 'job', 'pronunciation': 'Shi-goto', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'いしゃ', 'translation': 'doctor', 'pronunciation': 'Isha', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'かいしゃいん', 'translation': 'office worker', 'pronunciation': 'Kaisha in', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'こうこうせい', 'translation': 'high school student', 'pronunciation': 'Kōkōsei', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'しゅふ', 'translation': 'housewife', 'pronunciation': 'Shyufu', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'だいがくいんせい', 'translation': 'graduate student', 'pronunciation': 'Dai ga kuin sei', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'だいがくせい', 'translation': 'college student', 'pronunciation': 'Dai ga ku sei', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'べんごし', 'translation': 'lawyer', 'pronunciation': 'Be n goshi', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'おかあさん','translation': 'mother','pronunciation': 'Okāsan','language': '','category': 'Family'},
    {'name': 'おとおさん', 'translation': 'father', 'pronunciation': 'O tō-san', 'language': 'ja', 'category': 'Family'},
    {'name': 'おねえさん', 'translation': 'older sister', 'pronunciation': 'O nēsan', 'language': 'ja', 'category': 'Family'},
    {'name': 'おにいさん', 'translation': 'older brother', 'pronunciation': 'O nīsan', 'language': 'ja', 'category': 'Family'},
    {'name': 'いもうと', 'translation': 'younger sister', 'pronunciation': 'Imou to', 'language': 'ja', 'category': 'Family'},
    {'name': 'おとうと', 'translation': 'younger brother', 'pronunciation': 'O tōto', 'language': 'ja', 'category': 'Family'},
    {'name': 'すうじ', 'translation': 'Numbers', 'pronunciation': 'Sūji', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ゼロ', 'translation': 'zero', 'pronunciation': 'Zero', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'いち', 'translation': 'one', 'pronunciation': 'Ichi', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'に', 'translation': 'two', 'pronunciation': 'ni', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'さん', 'translation': 'three', 'pronunciation': 'San', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'よん', 'translation': 'four', 'pronunciation': 'yon', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ご', 'translation': 'five', 'pronunciation': 'go', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ろく', 'translation': 'six', 'pronunciation': 'roku', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'なな', 'translation': 'seven', 'pronunciation': 'nana', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'はち', 'translation': 'eight', 'pronunciation': 'hachi', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'きゅう', 'translation': 'nine', 'pronunciation': 'Kyū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅう', 'translation': 'ten', 'pronunciation': 'Jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅういち', 'translation': 'eleven', 'pronunciation': 'Jū ichi', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうに', 'translation': 'twelve', 'pronunciation': 'Jū ni', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうさん', 'translation': 'thirteen', 'pronunciation': 'Jū-san', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうよん', 'translation': 'fourteen', 'pronunciation': 'Jū yo n', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうご', 'translation': 'fifteen', 'pronunciation': 'Jū go', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうろく', 'translation': 'sixteen', 'pronunciation': 'Jyuuroku', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうなな', 'translation': 'seventeen', 'pronunciation': 'Jūna na', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうはち', 'translation': 'eighteen', 'pronunciation': 'Jyuuhachi', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'じゅうきゅう', 'translation': 'nineteen', 'pronunciation': 'Jū kyū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'にじゅう', 'translation': 'twenty', 'pronunciation': 'Ni jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'さんじゅう', 'translation': 'thirty', 'pronunciation': 'San-jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'よんじゅう', 'translation': 'fourty', 'pronunciation': 'Yon jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ごじゅう', 'translation': 'fifty', 'pronunciation': 'Go jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ろくじゅう', 'translation': 'sixty', 'pronunciation': 'Ro kujū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ななじゅう', 'translation': 'seventy', 'pronunciation': 'Nana-jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'はちじゅう', 'translation': 'eighty', 'pronunciation': 'ha chi jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'きゅうじゅう', 'translation': 'ninety', 'pronunciation': 'Kyū-jū', 'language': 'ja', 'category': 'Numbers'},
    {'name': 'ひゃく', 'translation': 'hundred', 'pronunciation': 'Hyaku', 'language': 'ja', 'category': 'Numbers'},
]