"""
File with list of words for GlobalWord model.
Dictionary format: {'name': '','translation': '','pronunciation': '','language': '', 'translate_language': '', 'category': ''}
"""
ja_words = [
    {'name': 'あいさつ','translation': 'Greetings','pronunciation': 'Aisatsu','language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'おはよう','translation': 'good morning','pronunciation': 'Ohayō','language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'おはよう　ございます','translation': 'good morning polite','pronunciation': 'Ohayōgozaimasu','language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'こんにちは', 'translation': 'good afternoon', 'pronunciation': 'Konnichiwa', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'こんばんは', 'translation': 'good evening', 'pronunciation': 'Konbanwa', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'さようなら', 'translation': 'goodbye', 'pronunciation': 'Sayōnara', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'おやすみなさい', 'translation': 'good night', 'pronunciation': 'Oyasuminasai', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'ありがとう', 'translation': 'Thank you', 'pronunciation': 'Arigatō', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'ありがとう ございます', 'translation': 'Thank you polite', 'pronunciation': 'Arigatōgozaimasu', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'すみません', 'translation': 'Excuse me', 'pronunciation': 'Sumimasen', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'いいえ', 'translation': 'No, not at all', 'pronunciation': 'Īe', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'いってきます', 'translation': 'See you', 'pronunciation': 'Itte kimasu', 'language': 'ja', 'translate_language': 'en','category': 'Greetings'},
    {'name': 'いってらっしゃい', 'translation': 'Take care', 'pronunciation': 'Itte rasshai', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'ただいま', 'translation': 'I\'m home', 'pronunciation': 'Tadaima', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'おかえりなさい', 'translation': 'Welcome home', 'pronunciation': 'Okaerinasai', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'いただきます', 'translation': 'Thank you for the meal(before)', 'pronunciation': 'Itadakimasu', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'ごちそうさまでした', 'translation': 'Thank you for the meal (after)', 'pronunciation': 'Gochisōsamadeshita', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'はじめまして', 'translation': 'Nice to meet you', 'pronunciation': 'Hajimemashite', 'language': 'ja', 'translate_language': 'en', 'category': 'Greetings'},
    {'name': 'あたらしいともだち', 'translation': 'New Friends', 'pronunciation': 'Atarashī tomodachi', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'あの', 'translation': 'um', 'pronunciation': 'Ano', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'いま', 'translation': 'now', 'pronunciation': 'Ima', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'えいご', 'translation': 'English', 'pronunciation': 'Ei go', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'ええ', 'translation': 'yes', 'pronunciation': 'E e', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'がくせい', 'translation': 'student', 'pronunciation': 'Gaku see', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': '〜ご', 'translation': '...language', 'pronunciation': '〜 Go', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'こうこう', 'translation': 'high school', 'pronunciation': 'Kō kō', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'ごご', 'translation': 'p.m.', 'pronunciation': 'Go go', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'ごぜん', 'translation': 'a.m.', 'pronunciation': 'Go zen', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': '〜さい', 'translation': '...years old', 'pronunciation': '〜 Sai', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': '〜さん', 'translation': '...Mr.|Ms.', 'pronunciation': '〜-San', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': '〜じ', 'translation': 'o\'clock', 'pronunciation': '〜Ji', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': '〜じん', 'translation': '..people', 'pronunciation': '〜 Jin', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'せんこう', 'translation': 'major', 'pronunciation': 'Senkō', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'せんせい', 'translation': 'teacher', 'pronunciation': 'Sensei', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'そうです', 'translation': 'that\'s right', 'pronunciation': 'Sōdesu', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'そうですか', 'translation': 'Is that so?', 'pronunciation': 'Sōdesu ka', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'だいがく', 'translation': 'university', 'pronunciation': 'Dai gaku', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'でんわ', 'translation': 'telephone', 'pronunciation': 'Denwa', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'ともだち', 'translation': 'friend', 'pronunciation': 'Tomodachi', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'なまえ', 'translation': 'name', 'pronunciation': 'Na ma e', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'なん', 'translation': 'what', 'pronunciation': 'Nan', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'なに', 'translation': 'what', 'pronunciation': 'nani', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': '〜ねんせい', 'translation': 'year student', 'pronunciation': '〜 Nen sei', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'はい', 'translation': 'yes', 'pronunciation': 'Hai', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'はん', 'translation': 'half', 'pronunciation': 'Han', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'ばんごう', 'translation': 'number', 'pronunciation': 'Ban gou', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'りゅうがくせい', 'translation': 'international student', 'pronunciation': 'Ryuugakusei', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'わたし', 'translation': 'I', 'pronunciation': 'Watashi', 'language': 'ja', 'translate_language': 'en', 'category': 'New Friends'},
    {'name': 'アメリカ', 'translation': 'U.S.A.', 'pronunciation': 'Amerika', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'イギリス', 'translation': 'Britian', 'pronunciation': 'Igirisu', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'オーストラリア', 'translation': 'Australia', 'pronunciation': 'Ōsutoraria', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'かんこく', 'translation': 'Korea', 'pronunciation': 'Kan koku', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'スウェーデン', 'translation': 'Sweden', 'pronunciation': 'Suu~ēden', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'ちゅうごく', 'translation': 'China', 'pronunciation': 'Chyuugoku', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'にほん', 'translation': 'Japan', 'pronunciation': 'Ni hon', 'language': 'ja', 'translate_language': 'en', 'category': 'Countries'},
    {'name': 'かがく', 'translation': 'science', 'pronunciation': 'Ka gaku', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'アジアけんきゅう', 'translation': 'asian studies', 'pronunciation': 'Ajia kenkyū', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'けいざい', 'translation': 'economics', 'pronunciation': 'Keizai', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'こくさいかんけい', 'translation': 'international relations', 'pronunciation': 'Ko kusai kan kei', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'コンピューター', 'translation': 'computer', 'pronunciation': 'Konpyūtā', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'じんるいがく', 'translation': 'anthropology', 'pronunciation': 'Jin rui gaku', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'せいじ', 'translation': 'politics', 'pronunciation': 'Seiji', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'ビジネス', 'translation': 'business', 'pronunciation': 'Bijinesu', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'ぶんがく', 'translation': 'literature', 'pronunciation': 'Bun gaku', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'れきし', 'translation': 'history', 'pronunciation': 'Rekishi', 'language': 'ja', 'translate_language': 'en', 'category': 'Majors'},
    {'name': 'しごと', 'translation': 'job', 'pronunciation': 'Shi-goto', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'いしゃ', 'translation': 'doctor', 'pronunciation': 'Isha', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'かいしゃいん', 'translation': 'office worker', 'pronunciation': 'Kaisha in', 'translate_language': 'en', 'language': 'ja', 'category': 'Occupations'},
    {'name': 'こうこうせい', 'translation': 'high school student', 'pronunciation': 'Kōkōsei', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'しゅふ', 'translation': 'housewife', 'pronunciation': 'Shyufu', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'だいがくいんせい', 'translation': 'graduate student', 'pronunciation': 'Dai ga kuin sei', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'だいがくせい', 'translation': 'college student', 'pronunciation': 'Dai ga ku sei', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'べんごし', 'translation': 'lawyer', 'pronunciation': 'Be n goshi', 'language': 'ja', 'translate_language': 'en', 'category': 'Occupations'},
    {'name': 'おかあさん','translation': 'mother','pronunciation': 'Okāsan','language': 'ja', 'translate_language': 'en','category': 'Family'},
    {'name': 'おとおさん', 'translation': 'father', 'pronunciation': 'O tō-san', 'language': 'ja', 'translate_language': 'en', 'category': 'Family'},
    {'name': 'おねえさん', 'translation': 'older sister', 'pronunciation': 'O nēsan', 'language': 'ja', 'translate_language': 'en', 'category': 'Family'},
    {'name': 'おにいさん', 'translation': 'older brother', 'pronunciation': 'O nīsan', 'language': 'ja', 'translate_language': 'en', 'category': 'Family'},
    {'name': 'いもうと', 'translation': 'younger sister', 'pronunciation': 'Imou to', 'language': 'ja', 'translate_language': 'en', 'category': 'Family'},
    {'name': 'おとうと', 'translation': 'younger brother', 'pronunciation': 'O tōto', 'language': 'ja', 'translate_language': 'en', 'category': 'Family'},
    {'name': 'すうじ', 'translation': 'Numbers', 'pronunciation': 'Sūji', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ゼロ', 'translation': 'zero', 'pronunciation': 'Zero', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'いち', 'translation': 'one', 'pronunciation': 'Ichi', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'に', 'translation': 'two', 'pronunciation': 'ni', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'さん', 'translation': 'three', 'pronunciation': 'San', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'よん', 'translation': 'four', 'pronunciation': 'yon', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ご', 'translation': 'five', 'pronunciation': 'go', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ろく', 'translation': 'six', 'pronunciation': 'roku', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'なな', 'translation': 'seven', 'pronunciation': 'nana', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'はち', 'translation': 'eight', 'pronunciation': 'hachi', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'きゅう', 'translation': 'nine', 'pronunciation': 'Kyū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅう', 'translation': 'ten', 'pronunciation': 'Jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅういち', 'translation': 'eleven', 'pronunciation': 'Jū ichi', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうに', 'translation': 'twelve', 'pronunciation': 'Jū ni', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうさん', 'translation': 'thirteen', 'pronunciation': 'Jū-san', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうよん', 'translation': 'fourteen', 'pronunciation': 'Jū yo n', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうご', 'translation': 'fifteen', 'pronunciation': 'Jū go', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうろく', 'translation': 'sixteen', 'pronunciation': 'Jyuuroku', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうなな', 'translation': 'seventeen', 'pronunciation': 'Jūna na', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうはち', 'translation': 'eighteen', 'pronunciation': 'Jyuuhachi', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'じゅうきゅう', 'translation': 'nineteen', 'pronunciation': 'Jū kyū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'にじゅう', 'translation': 'twenty', 'pronunciation': 'Ni jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'さんじゅう', 'translation': 'thirty', 'pronunciation': 'San-jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'よんじゅう', 'translation': 'fourty', 'pronunciation': 'Yon jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ごじゅう', 'translation': 'fifty', 'pronunciation': 'Go jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ろくじゅう', 'translation': 'sixty', 'pronunciation': 'Ro kujū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ななじゅう', 'translation': 'seventy', 'pronunciation': 'Nana-jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'はちじゅう', 'translation': 'eighty', 'pronunciation': 'ha chi jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'きゅうじゅう', 'translation': 'ninety', 'pronunciation': 'Kyū-jū', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'ひゃく', 'translation': 'hundred', 'pronunciation': 'Hyaku', 'language': 'ja', 'translate_language': 'en', 'category': 'Numbers'},
    {'name': 'これ', 'translation': 'this one', 'pronunciation': 'koko', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'それ', 'translation': 'that one', 'pronunciation': 'sore', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'あの', 'translation': 'that one(over there)', 'pronunciation': 'are', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'どれ', 'translation': 'which one', 'pronunciation': 'dore', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'この', 'translation': 'this...', 'pronunciation': 'kono', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'その', 'translation': 'that...', 'pronunciation': 'sono', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'あの', 'translation': 'that...(over there)', 'pronunciation': 'ano', 'language': 'ja', 'translate_language': 'en','category': 'Words that point'},
    {'name': 'どの', 'translation': 'which', 'pronunciation': 'dono', 'language': 'ja', 'translate_language': 'en','category': 'Words that point'},
    {'name': 'ここ', 'translation': 'here', 'pronunciation': 'koko', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'そこ', 'translation': 'there', 'pronunciation': 'soko', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'あそこ', 'translation': 'over there', 'pronunciation': 'asoko', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'どこ', 'translation': 'where', 'pronunciation': 'doko', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'だれ', 'translation': 'who', 'pronunciation': 'dare', 'language': 'ja', 'translate_language': 'en', 'category': 'Words that point'},
    {'name': 'おいしい', 'translation': 'delicious', 'pronunciation': 'oishii', 'language': 'ja', 'translate_language': 'en', 'category': 'Food'},
    {'name': 'さかな', 'translation': 'fish', 'pronunciation': 'sakana', 'language': 'ja', 'translate_language': 'en', 'category': 'Food'},
    {'name': 'とんかつ', 'translation': 'pork cutlet', 'pronunciation': 'tonkatsu', 'language': 'ja', 'translate_language': 'en', 'category': 'Food'},
    {'name': 'にく', 'translation': 'meat', 'pronunciation': 'niku', 'language': 'ja', 'translate_language': 'en', 'category': 'Food'},
    {'name': 'メニュー', 'translation': 'menu', 'pronunciation': 'menyuu', 'language': 'ja', 'translate_language': 'en', 'category': 'Food'},
    {'name': 'やさい', 'translation': 'vegetable', 'pronunciation': 'yasai', 'language': 'ja', 'translate_language': 'en', 'category': 'Food'},
    {'name': 'えんぴつ', 'translation': 'pencil', 'pronunciation': 'enpitsu', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'かさ', 'translation': 'umbrella', 'pronunciation': 'kasa', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'かばｎ', 'translation': 'bag', 'pronunciation': 'kaban', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'くつ', 'translation': 'shoes', 'pronunciation': 'kutsu', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'さいふ', 'translation': 'wallet', 'pronunciation': 'saify', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'ジーンズ', 'translation': 'jeans', 'pronunciation': 'jiinzu', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'じしょ', 'translation': 'dictionary', 'pronunciation': 'jisho', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'じてんしゃ', 'translation': 'newspaper', 'pronunciation': 'shinbun', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'しんぶん', 'translation': 'bicycle', 'pronunciation': 'jitensha', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'Tシャツ', 'translation': 'T-shirt', 'pronunciation': 'tiishatsu', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'とけい', 'translation': 'watch', 'pronunciation': 'tokee', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'ノート', 'translation': 'notebook', 'pronunciation': 'nooto', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'ぺん', 'translation': 'pen', 'pronunciation': 'pen', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'ぼうし', 'translation': 'hat', 'pronunciation': 'booshi', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'ほん', 'translation': 'book', 'pronunciation': 'hon', 'language': 'ja', 'translate_language': 'en', 'category': 'Things'},
    {'name': 'きっさてん', 'translation': 'cafe', 'pronunciation': 'kissaten', 'language': 'ja', 'translate_language': 'en', 'category': 'Places'},
    {'name': 'ぎんこう', 'translation': 'bank', 'pronunciation': 'ginkoo', 'language': 'ja', 'translate_language': 'en', 'category': 'Places'},
    {'name': 'トイレ', 'translation': 'toilet', 'pronunciation': 'toire', 'language': 'ja', 'translate_language': 'en', 'category': 'Places'},
    {'name': 'としょかん', 'translation': 'library', 'pronunciation': 'toshokan', 'language': 'ja', 'translate_language': 'en', 'category': 'Places'},
    {'name': 'ゆびんきょく', 'translation': 'post office', 'pronunciation': 'yuubinkyoku', 'language': 'ja', 'translate_language': 'en', 'category': 'Places'},
    {'name': 'いくら', 'translation': 'how much', 'pronunciation': 'ikura', 'language': 'ja', 'translate_language': 'en', 'category': 'Money matter'},
    {'name': '～えん', 'translation': '...yen', 'pronunciation': '...en', 'language': 'ja', 'translate_language': 'en', 'category': 'Money matter'},
    {'name': 'たかい', 'translation': 'expensive', 'pronunciation': 'takai', 'language': 'ja', 'translate_language': 'en', 'category': 'Money matter'},
    {'name': 'いらっしゃいませ', 'translation': 'Welcome', 'pronunciation': 'irasshaimase', 'language': 'ja', 'translate_language': 'en', 'category': 'Expressions'},
    {'name': '（～を）おねがいしまｓｙ', 'translation': '...,please', 'pronunciation': '(...0)onegaishimasu', 'language': 'ja', 'translate_language': 'en', 'category': 'Expressions'},
    {'name': '（～を）ください', 'translation': 'Please give me...', 'pronunciation': '(...0)kudasai', 'language': 'ja', 'translate_language': 'en', 'category': 'Expressions'},
    {'name': 'じゃあ', 'translation': 'then...', 'pronunciation': 'jaa', 'language': 'ja', 'translate_language': 'en', 'category': 'Expressions'},
    {'name': 'どうぞ', 'translation': 'Please', 'pronunciation': 'doozo', 'language': 'ja', 'translate_language': 'en', 'category': 'Expressions'},
    {'name': 'どうも', 'translation': 'Thank you', 'pronunciation': 'doomo', 'language': 'ja', 'translate_language': 'en', 'category': 'Expressions'},


]