# Generated by Django 2.0.2 on 2018-02-13 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linguist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguist.Language'),
        ),
        migrations.AddField(
            model_name='category',
            name='global_word',
            field=models.ManyToManyField(to='linguist.GlobalWord'),
        ),
        migrations.AddField(
            model_name='category',
            name='word',
            field=models.ManyToManyField(to='linguist.Word'),
        ),
    ]
