# Generated by Django 2.0.2 on 2018-03-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linguist', '0003_auto_20180218_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalword',
            name='translate_language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='translate_langs', to='linguist.Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='linguist.Language'),
        ),
    ]
